version: "3.9"
services:
  swagger:
    image: swaggerapi/swagger-ui:v4.18.1
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://127.0.0.1:8000/swagger.json
  swagger-editor:
    image: swaggerapi/swagger-editor:v4.9.0
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://127.0.0.1:8000/swagger.json
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - POSTGRES_HOST_AUTH_METHOD=trust
      - SERVICE_MANAGER= "fsm-postgres"
    volumes:
      - ./db:/var/lib/postgresql/data
  python-web:
    build: .
    restart: always
    depends_on:
      - postgresql
    volumes:
      - ./web:/var/www
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"