version: "3.9"
services:
  swagger:
    image: swaggerapi/swagger-ui:3.18.2
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://python-web:8000/swagger.json
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB= "db"
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - SERVICE_MANAGER= "fsm-postgres"
    volumes:
      - ./db:/var/lib/postgresql/data
  python-web:
    build: .
    restart: always
    volumes:
      - ./web:/var/www
    command: python manage.py runserver
    ports:
      - "8000:8000"